# Generated by Django 6.0.3 on 2026-04-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("instituicao", models.CharField(max_length=200)),
                ("area", models.CharField(max_length=100)),
                ("duracao_anos", models.IntegerField()),
                ("descricao", models.TextField(blank=True)),
                ("link", models.URLField(blank=True)),
            ],
        ),
    ]
