# Generated by Django 6.0.3 on 2026-04-07 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("ano", models.IntegerField()),
                (
                    "semestre",
                    models.IntegerField(choices=[(1, "Semestre 1"), (2, "Semestre 2")]),
                ),
                ("descricao", models.TextField(blank=True)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="unidades/"),
                ),
                ("docente_nome", models.CharField(blank=True, max_length=200)),
                ("docente_link", models.URLField(blank=True)),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidades",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
    ]
