# Generated by Django 6.0.3 on 2026-04-07 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_unidadecurricular"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "tecnologias",
                    models.TextField(help_text="Ex: Python, Django, HTML, CSS"),
                ),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="projetos/"),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, help_text="Link para video demo no YouTube"
                    ),
                ),
                ("link_github", models.URLField(blank=True)),
                ("data", models.DateField(blank=True, null=True)),
                (
                    "conceitos_aplicados",
                    models.TextField(
                        blank=True, help_text="Conceitos da UC aplicados neste projeto"
                    ),
                ),
                (
                    "unidade_curricular",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projetos",
                        to="portfolio.unidadecurricular",
                    ),
                ),
            ],
        ),
    ]
