# Generated by Django 6.0.3 on 2026-04-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_projeto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("linguagem", "Linguagem de Programação"),
                            ("framework", "Framework"),
                            ("base_dados", "Base de Dados"),
                            ("ferramenta", "Ferramenta"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
                ),
                ("link_oficial", models.URLField(blank=True)),
                (
                    "nivel_interesse",
                    models.IntegerField(
                        choices=[
                            (1, "⭐ Iniciante"),
                            (2, "⭐⭐ Básico"),
                            (3, "⭐⭐⭐ Intermédio"),
                            (4, "⭐⭐⭐⭐ Avançado"),
                            (5, "⭐⭐⭐⭐⭐ Expert"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "projetos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tecnologias_usadas",
                        to="portfolio.projeto",
                    ),
                ),
            ],
        ),
    ]
