# Generated by Django 6.0.3 on 2026-04-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_tecnologia"),
    ]

    operations = [
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autor", models.CharField(max_length=200)),
                ("ano", models.IntegerField()),
                ("descricao", models.TextField(blank=True)),
                ("tecnologias", models.CharField(blank=True, max_length=200)),
                ("link", models.URLField(blank=True)),
                (
                    "classificacao_interesse",
                    models.IntegerField(
                        choices=[
                            (1, "⭐ Pouco interessante"),
                            (2, "⭐⭐ Interessante"),
                            (3, "⭐⭐⭐ Muito interessante"),
                        ],
                        default=2,
                    ),
                ),
            ],
        ),
    ]
