# Generated by Django 6.0.3 on 2026-04-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_tfc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tfc",
            name="autor",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="descricao",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="link",
        ),
        migrations.AddField(
            model_name="tfc",
            name="areas",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="autores",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tfc",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="tfc",
            name="imagem_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="licenciatura",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="tfc",
            name="link_pdf",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="orientadores",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="palavras_chave",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="resumo",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="ano",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="tecnologias",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="titulo",
            field=models.CharField(max_length=500),
        ),
    ]
