# Generated by Django 6.0.3 on 2026-04-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_competencia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("instituicao", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("academica", "Académica"),
                            ("curso", "Curso Online"),
                            ("certificacao", "Certificação"),
                            ("workshop", "Workshop"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("em_curso", models.BooleanField(default=False)),
                (
                    "certificado",
                    models.FileField(blank=True, null=True, upload_to="certificados/"),
                ),
                ("link", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["-data_inicio"],
            },
        ),
    ]
