# Generated by Django 6.0.3 on 2026-04-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_formacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("decisao", "Decisão de Modelação"),
                            ("erro", "Erro e Correção"),
                            ("diagrama", "Diagrama/Esquema"),
                            ("foto", "Foto do Caderno"),
                            ("ia", "Uso de IA"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descricao", models.TextField()),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="makingof/"),
                ),
                ("data", models.DateField(auto_now_add=True)),
                (
                    "entidade_relacionada",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Licenciatura, Projeto, TFC...",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Making Of",
                "verbose_name_plural": "Making Of",
                "ordering": ["-data"],
            },
        ),
    ]
