# Generated by Django 6.0.3 on 2026-04-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_makingof"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("hackathon", "Hackathon"),
                            ("conferencia", "Conferência"),
                            ("workshop", "Workshop"),
                            ("seminario", "Seminário"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("local", models.CharField(blank=True, max_length=200)),
                ("data", models.DateField()),
                ("link", models.URLField(blank=True)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="eventos/"),
                ),
                (
                    "certificado",
                    models.FileField(
                        blank=True, null=True, upload_to="eventos/certificados/"
                    ),
                ),
            ],
            options={
                "ordering": ["-data"],
            },
        ),
    ]
