# Generated by Django 6.0.4 on 2026-04-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_evento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("conferencia", "Conferência"),
                    ("workshop", "Workshop"),
                    ("seminario", "Seminário"),
                    ("outro", "Outro"),
                ],
                max_length=50,
            ),
        ),
    ]
